language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t benielvernost/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true benielvernost/docker-react npm run test